// react/src/app/login/page.tsx
"use client";

import { loginApi } from "@/services/authService";
import { useAuthStore } from "@/services/authStore";
import { useRouter } from "next/navigation";
import { useState } from "react";

export default function Login() {
  const [loginError, setLoginError] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");

  const { login } = useAuthStore();
  const router = useRouter();

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setIsLoading(true);
    try {
      const { user, accessToken } = await loginApi(username, password);
      login(user, accessToken);

      router.push("/dashboard");
    } catch (error) {
      if (error instanceof Error) {
        setLoginError(error.message);
      } else {
        setLoginError("Une erreur est survenue lors de la connexion.");
      }
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <main className="rpgui-container framed flex justify-center items-center py-20!">
      <div className="rpgui-container framed-golden max-w-md w-full p-6">
        <h1 className="!text-2xl text-center">RPG Adventure</h1>
        <hr className="golden mb-8" />

        <div className="flex justify-center mb-6">
          <div className="rpgui-icon shield-slot" style={{ width: "80px", height: "80px" }}></div>
        </div>

        <div className="mb-4 p-3 rpgui-container framed-grey-sm text-red-500 text-center">{loginError}</div>

        <form onSubmit={handleSubmit}>
          <div className="mb-6">
            <label className="block mb-2">Nom d&apos;aventurier</label>
            <input
              type="text"
              className="rpgui-input mb-1 w-full"
              placeholder="Entrez votre nom d'aventurier"
              onChange={(e) => setUsername(e.target.value)}
            />
          </div>

          <div className="mb-6">
            <label className="block mb-2">Mot de passe</label>
            <input
              type="password"
              className="rpgui-input mb-1 w-full"
              placeholder="Entrez votre mot de passe"
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>

          <div className="flex flex-col gap-3">
            {isLoading ? (
              <button className="rpgui-button golden" disabled>
                <p>Chargement...</p>
              </button>
            ) : (
              <button type="submit" className="rpgui-button golden">
                <p>SE CONNECTER</p>
              </button>
            )}
          </div>
        </form>

        <hr className="golden my-6" />

        <div className="text-center">
          <p className="mb-4">Pas encore de compte?</p>
          <a href="/register" className="rpgui-button golden">
            <p>CRÉER UN COMPTE</p>
          </a>
        </div>
      </div>
    </main>
  );
}

// vue/src/views/Login.vue
<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'

// Initialisation des variables réactives
const loginForm = reactive({
  username: '',
  password: '',
})

const loginError = ref<string | null>(null)
const usernameError = ref<string | null>(null)
const passwordError = ref<string | null>(null)
const router = useRouter()
const authStore = useAuthStore()

// Validation simple du formulaire
const validateForm = () => {
  let isValid = true

  // Validation du nom d'utilisateur
  if (!loginForm.username.trim()) {
    usernameError.value = "Nom d'aventurier requis"
    isValid = false
  } else {
    usernameError.value = null
  }

  // Validation du mot de passe
  if (!loginForm.password.trim()) {
    passwordError.value = 'Mot de passe requis'
    isValid = false
  } else {
    passwordError.value = null
  }

  return isValid
}

// Soumission du formulaire
const onSubmit = async () => {
  if (validateForm()) {
    loginError.value = null

    try {
      await authStore.login({
        username: loginForm.username,
        password: loginForm.password,
      })
      // La redirection est gérée dans le store d'authentification
      console.log('Login successful')
    } catch (error) {
      console.error('Login failed:', error)
      loginError.value = 'Identifiants incorrects. Veuillez réessayer.'
    }
  }
}
</script>

<template>
  <main class="rpgui-container framed flex justify-center items-center py-20!">
    <div class="rpgui-container framed-golden max-w-md w-full p-6">
      <h1 class="!text-2xl text-center">RPG Adventure</h1>
      <hr class="golden mb-8" />

      <!-- Message d'erreur -->
      <div
        v-if="loginError"
        class="mb-4 p-3 rpgui-container framed-grey-sm text-red-500 text-center"
      >
        {{ loginError }}
      </div>

      <!-- Formulaire de connexion -->
      <form @submit.prevent="onSubmit">
        <div class="mb-6">
          <label class="block mb-2">Nom d'aventurier</label>
          <input
            type="text"
            v-model="loginForm.username"
            class="rpgui-input mb-1 w-full"
            placeholder="Entrez votre nom d'aventurier"
          />
          <div v-if="usernameError" class="text-red-400 text-sm">
            {{ usernameError }}
          </div>
        </div>

        <div class="mb-6">
          <label class="block mb-2">Mot de passe</label>
          <input
            type="password"
            v-model="loginForm.password"
            class="rpgui-input mb-1 w-full"
            placeholder="Entrez votre mot de passe"
          />
          <div v-if="passwordError" class="text-red-400 text-sm">
            {{ passwordError }}
          </div>
        </div>

        <div class="flex flex-col gap-3">
          <button
            type="submit"
            class="rpgui-button"
            :disabled="!loginForm.username || !loginForm.password"
          >
            <p>COMMENCER L'AVENTURE</p>
          </button>
        </div>
      </form>

      <hr class="golden my-6" />

      <!-- Pas encore de compte -->
      <div class="text-center">
        <p class="mb-4">Pas encore de compte?</p>
        <router-link to="/register" class="rpgui-button golden">
          <p>CRÉER UN COMPTE</p>
        </router-link>
      </div>
    </div>
  </main>
</template>
